### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kohli-rahul** [iocanel/quarkus-authzed-client#8]
[libprotobuf WARNING T:\src\github\protobuf\src\google\protobuf\compiler\java\java_file.cc:232] authzed/api/v1alpha1/watchresources_service.proto: The file's outer class name, "WatchresourcesService", matches the name of one of the types declared inside it when case is ignored. This can cause compilation issues on Windows / MacOS. Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file to be safe.
[INFO] [io.quarkus.grpc.deployment.GrpcCodeGen] Successfully finished generating and post-processing sources from proto files
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-authzed-grpc ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 51 source files to C:\Users\rahul.kohli\projects\quarkus-authzed-client\authzed-grpc\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/rahul.kohli/projects/quarkus-authzed-client/authzed-grpc/target/generated-sources/grpc/com/authzed/api/v1alpha1/WatchResourcesService.java:[5,14] class WatchresourcesService is public, should be declared in a file named WatchresourcesService.java
[ERROR] /C:/Users/rahul.kohli/projects/quarkus-authzed-client/authzed-grpc/target/generated-sources/grpc/com/authzed/api/v1alpha1/WatchResourcesServiceClient.java:[7,53] cannot access com.authzed.api.v1alpha1.WatchResourcesService
  bad source file: C:\Users\rahul.kohli\projects\quarkus-authzed-client\authzed-grpc\target\generated-sources\grpc\com\authzed\api\v1alpha1\WatchResourcesService.java
    file does not contain class com.authzed.api.v1alpha1.WatchResourcesService
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
[ERROR] /C:/Users/rahul.kohli/projects/quarkus-authzed-client/authzed-grpc/target/generated-sources/grpc/com/authzed/api/v1alpha1/WatchResourcesServiceClient.java:[28,5] method does not override or implement a method from a supertype

**Comment by iocanel** [comment]
Weird. I am wondering if it's a windows issue.

**Comment by iocanel** [comment]
As of #22 code generation happens optionally via github actions. So, this issue should not really happen. Feel free to re-open if you hit other issues down the road. Thanks for the feedback.

**Comment by kohli-rahul** [comment]
Still getting compile time issues after latest pull as well, so reopening the issue
